uploads = []
generated = []

[[outputs]]
id = "5vf3oay3-kTy_PGDbK9Pm"
uri = "file://KyNiemLop9A2_Part1_SourceCode.zip"
type = "unspecified"
title = "Phần 1 — Source Code + Ảnh (1.5 MB)"

[[outputs]]
id = "5KpMwDuHQRrjcpKECow_9"
uri = "file://KyNiemLop9A2_Part2_NhacMP3.zip"
type = "unspecified"
title = "Phần 2 — Nhạc nền MP3 (8.9 MB)"
